version: '3'
services:
  qr_postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - qr_postgres
    env_file:
      - .env
    ports:
      - "8001:8001"

volumes:
  postgres_data:
